version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/frontend/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    command: npm run server

volumes:
  app-data: